In [1]:
import numpy as np
import pandas as pd

In [2]:
movies=pd.read_csv('tmdb_5000_movies.csv')
credits=pd.read_csv('tmdb_5000_credits.csv')

In [3]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [4]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [5]:
#merging both dataframes
movies=movies.merge(credits,on='title')

In [6]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 901.7+ KB

In [7]:
#extracting selected columns which i want to use 
movies=movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [8]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [9]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [10]:
#droping movies whch have null values in overview
movies.dropna(inplace=True)

In [11]:
#checking duplicate values in dataset
movies.duplicated().sum()

0

In [12]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

function tolist to extract only useful index of dictionaries like only name from genres dictionary

In [13]:

import ast
#importing ast to convert string which we are getting as input
# into a list so that we can iterate over it.
def tolist(obj):
    L=[]
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [14]:

movies['genres']=movies['genres'].apply(tolist)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [15]:
movies['keywords']=movies['keywords'].apply(tolist)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [16]:
movies['cast'][0]

'[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'

In [17]:

#function to find top four cast members in a movie
import ast
def maincast(obj):
    L=[]
    count=0;
    for i in ast.literal_eval(obj):
        if(count<4):
            L.append(i['name'])
            count+=1
        else:
            break
    return L

In [18]:
movies['cast']=movies['cast'].apply(maincast)
movies['cast'][0]

['Sam Worthington', 'Zoe Saldana', 'Sigourney Weaver', 'Stephen Lang']

In [19]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [20]:
#function to extract only director name from crew column
def director(obj):
    L=[]
    for i in ast.literal_eval(obj):
        if(i['job']=='Director'):
            L.append(i['name'])
            break
    return L

In [21]:
movies['crew']=movies['crew'].apply(director)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton]

In [22]:
#to convert overview from string to a list so that we can concatenate it with other columns to get tags for a movie
movies['overview']=movies['overview'].apply(lambda i:i.split())
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton]

In [23]:
#removing spaces from each column because it can create ambiguity
movies['genres']=movies['genres'].apply(lambda x:[ i.replace(" ","") for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","")for i in x])
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux, Ralp...",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman, Anne...",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton]

In [24]:
#making another column which is tags which is basis of our reccomendation
movies['tags']=movies['overview']+movies['genres']+movies['keywords']+movies['cast']+movies['crew']
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux, Ralp...",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman, Anne...",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [25]:
movies_new=movies[['movie_id','title','overview','tags']]
movies_new.head()

,movie_id,title,overview,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[John, Carter, is, a, war-weary,, former, mili..."

In [26]:
#converting list to string in tags column
movies_new['tags']=movies_new['tags'].apply(lambda x:" ".join(x))

C:\Users\Shresht\AppData\Local\Temp\ipykernel_13112\1451928080.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_new['tags']=movies_new['tags'].apply(lambda x:" ".join(x))

In [27]:
movies_new.head()

,movie_id,title,overview,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...",A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...",Following the death of District Attorney Harve...
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","John Carter is a war-weary, former military ca..."

In [28]:
movies_new['overview']=movies_new['overview'].apply(lambda x:" ".join(x))

C:\Users\Shresht\AppData\Local\Temp\ipykernel_13112\1302030681.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_new['overview']=movies_new['overview'].apply(lambda x:" ".join(x))

In [29]:
movies_new.head()

,movie_id,title,overview,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca...","John Carter is a war-weary, former military ca..."

In [30]:
movies_new['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver StephenLang JamesCameron'

In [31]:
#converting whole string to lowercase
movies_new['tags']=movies_new['tags'].apply(lambda x:x.lower())

C:\Users\Shresht\AppData\Local\Temp\ipykernel_13112\2279423770.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_new['tags']=movies_new['tags'].apply(lambda x:x.lower())

In [32]:
movies_new.tail()

,movie_id,title,overview,tags
4804,9367,El Mariachi,El Mariachi just wants to play his guitar and ...,el mariachi just wants to play his guitar and ...
4805,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...,a newlywed couple's honeymoon is upended by th...
4806,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...","""signed, sealed, delivered"" introduces a dedic..."
4807,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...,when ambitious new york attorney sam is sent t...
4808,25975,My Date with Drew,Ever since the second grade when he first saw ...,ever since the second grade when he first saw ...

preprocessing of data is done

BUILDING MAIN MODEL

In [33]:
#performing stemming on our tags so that words with similar meaning can't be considered as different words
import nltk
from nltk.stem.porter import PorterStemmer
#making an object of porter scanner.
st=PorterStemmer()
def stemtag(tag):
    L=[]
    for i in tag.split():
        L.append(st.stem(i))

    new_tag=" ".join(L)
    return new_tag

In [34]:
movies_new['tags']=movies_new['tags'].apply(stemtag)
movies_new['tags'][0]
movies_new.tail()

C:\Users\Shresht\AppData\Local\Temp\ipykernel_13112\854450326.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_new['tags']=movies_new['tags'].apply(stemtag)

,movie_id,title,overview,tags
4804,9367,El Mariachi,El Mariachi just wants to play his guitar and ...,el mariachi just want to play hi guitar and ca...
4805,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...,a newlyw couple' honeymoon is upend by the arr...
4806,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...","""signed, sealed, delivered"" introduc a dedic q..."
4807,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...,when ambiti new york attorney sam is sent to s...
4808,25975,My Date with Drew,Ever since the second grade when he first saw ...,ever sinc the second grade when he first saw h...

In [35]:
from sklearn.feature_extraction.text import TfidfVectorizer
#creating a object cv which will help in vectorization
cv=TfidfVectorizer(max_features=5000,stop_words='english')

In [36]:
vectors=cv.fit_transform(movies_new['tags']).toarray()
#.toarray is used to convert sparse matrix which is returned 
#by countvectorizer function into a numpy array
print(vectors)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

In [37]:
cv.get_feature_names()

C:\Users\Shresht\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '18th',
 '19',
 '1910',
 '1920',
 '1930',
 '1940',
 '1950',
 '1950s',
 '1960',
 '1960s',
 '1970',
 '1970s',
 '1980',
 '1985',
 '1990',
 '19th',
 '19thcenturi',
 '20',
 '200',
 '2009',
 '20th',
 '24',
 '25',
 '30',
 '300',
 '3d',
 '40',
 '50',
 '500',
 '60',
 '70',
 'aaron',
 'aaroneckhart',
 'aarontaylor',
 'abandon',
 'abduct',
 'abigailbreslin',
 'abil',
 'abl',
 'aboard',
 'abov',
 'abus',
 'academ',
 'academi',
 'accept',
 'access',
 'accid',
 'accident',
 'acclaim',
 'accompani',
 'accomplish',
 'account',
 'accus',
 'ace',
 'achiev',
 'acquaint',
 'act',
 'action',
 'actionhero',
 'activ',
 'activist',
 'activities',
 'actor',
 'actress',
 'actual',
 'ad',
 'adam',
 'adambrodi',
 'adamsandl',
 'adamshankman',
 'adapt',
 'add',
 'addict',
 'adjust',
 'admir',
 'admit',
 'adolesc',
 'adopt',
 'ador',
 'adrienbrodi',
 'adult',
 'adultanim',
 'adulteri',
 'adulthood',
 'advanc',
 'adventur',
 'adventure',
 'adventures',
 'advertis',
 'advic',
 'advis',
 'affair',
 'affect',
 'afghanistan',
 'africa',
 'african',
 'africanamerican',
 'aftercreditssting',
 'afterlif',
 'aftermath',
 'ag',
 'age',
 'agediffer',
 'agenc',
 'agency',
 'agenda',
 'agent',
 'agents',
 'aggress',
 'ago',
 'agre',
 'ahead',
 'aid',
 'aidanquinn',
 'ail',
 'aim',
 'air',
 'airplan',
 'airplanecrash',
 'airport',
 'aka',
 'al',
 'alabama',
 'alan',
 'alanalda',
 'alanarkin',
 'alaska',
 'albert',
 'albertbrook',
 'alcohol',
 'alecbaldwin',
 'alex',
 'alexkendrick',
 'alfredhitchcock',
 'alfredmolina',
 'alfrewoodard',
 'ali',
 'alic',
 'alice',
 'alicebraga',
 'alien',
 'alieninvas',
 'alienlife',
 'alienplanet',
 'aliens',
 'alik',
 'aliv',
 'alive',
 'allen',
 'alli',
 'allianc',
 'allow',
 'alon',
 'alongsid',
 'alpacino',
 'alpha',
 'alreadi',
 'alter',
 'altern',
 'alway',
 'alzheimer',
 'amanda',
 'amandapeet',
 'amandaseyfri',
 'amateur',
 'amaz',
 'ambassador',
 'ambit',
 'ambiti',
 'ambul',
 'ambush',
 'america',
 'american',
 'americanabroad',
 'americanfootbal',
 'amid',
 'amidst',
 'amnesia',
 'amp',
 'amsterdam',
 'amus',
 'amusementpark',
 'amy',
 'amyadam',
 'amysmart',
 'analyst',
 'anarchiccomedi',
 'ancient',
 'ancientrom',
 'ancientworld',
 'anderson',
 'andi',
 'andiemacdowel',
 'andrew',
 'android',
 'andy',
 'andygarcía',
 'andyserki',
 'angel',
 'angela',
 'angelabassett',
 'angeles',
 'angelinajoli',
 'anger',
 'angle',
 'angri',
 'ani',
 'anim',
 'animalattack',
 'animalhorror',
 'animals',
 'anjelicahuston',
 'ann',
 'anna',
 'annafari',
 'annakendrick',
 'annasophiarobb',
 'anne',
 'annehathaway',
 'annemoss',
 'annetteben',
 'anni',
 'annie',
 'announc',
 'annual',
 'anonym',
 'anoth',
 'answer',
 'ant',
 'antholog',
 'anthoni',
 'anthonyanderson',
 'anthonyhopkin',
 'anthonymacki',
 'anthropomorph',
 'anti',
 'antihero',
 'antoinefuqua',
 'antoniobandera',
 'antonyelchin',
 'anyon',
 'anyth',
 'apart',
 'apartheid',
 'apartment',
 'ape',
 'apocalyps',
 'apocalypt',
 'appar',
 'appear',
 'appl',
 'appoint',
 'appreci',
 'apprentic',
 'approach',
 'april',
 'aquarium',
 'arab',
 'arch',
 'archaeologist',
 'archeolog',
 'archer',
 'architect',
 'arctic',
 'area',
 'aren',
 'arena',
 'argument',
 'aris',
 'aristocrat',
 'arm',
 'armi',
 'armiehamm',
 'armor',
 'armsdeal',
 'army',
 'arnold',
 'arnoldschwarzenegg',
 'arrang',
 'arrangedmarriag',
 'arrest',
 'arriv',
 'arrog',
 'art',
 'arthur',
 'artifact',
 'artifici',
 'artificialintellig',
 'artist',
 'ash',
 'ashley',
 'ashleyjudd',
 'ashtonkutch',
 'asia',
 'asian',
 'asid',
 'ask',
 'aspect',
 'aspir',
 'assassin',
 'assault',
 'assembl',
 'assign',
 'assist',
 'assistant',
 'associ',
 'assum',
 'asteroid',
 'astronaut',
 'asylum',
 'atheist',
 'athlet',
 'atom',
 'atomicbomb',
 'attack',
 'attacks',
 'attempt',
 'attempttoescap',
 'attend',
 'attent',
 'attic',
 'attitud',
 'attorney',
 'attract',
 'auction',
 'audienc',
 'audit',
 'august',
 'aunt',
 'austin',
 'australia',
 'australian',
 'author',
 'autism',
 'auto',
 'aveng',
 'averag',
 'avoid',
 'await',
 'awaken',
 'award',
 'away',
 'awkward',
 'awri',
 'awry',
 'ax',
 'babe',
 'babi',
 'baby',
 'bachelor',
 'backdrop',
 'background',
 'backpack',
 'bad',
 'bag',
 'bahama',
 'bail',
 'balanc',
 'ball',
 'ballet',
 'balloon',
 'band',
 'bandit',
 'bangkok',
 'banish',
 'bank',
 'banker',
 'bankrobb',
 'bankrobberi',
 'bar',
 'bare',
 'bargain',
 'barn',
 'barney',
 'baron',
 'barri',
 'barrylevinson',
 'barrypepp',
 'bas',
 'base',
 'basebal',
 'basedoncomicbook',
 'basedongraphicnovel',
 'basedonnovel',
 'basedonplay',
 'basedonstagemus',
 'basedontrueev',
 'basedontruestori',
 'basedontvseri',
 'basedonvideogam',
 'basedonyoungadultnovel',
 'basement',
 'basketbal',
 'batman',
 'battl',
 'battle',
 'battlefield',
 'bay',
 'beach',
 'bear',
 'beast',
 'beat',
 'beauti',
 'beautiful',
 'beautifulwoman',
 'beauty',
 'becam',
 'becaus',
 'becom',
 'becominganadult',
 'bed',
 'bedroom',
 'beer',
 'befor',
 'befriend',
 'began',
 'begin',
 'begins',
 'behavior',
 'belief',
 'believ',
 'bell',
 'bella',
 'belong',
 'belov',
 'ben',
 'benaffleck',
 'bend',
 'beneath',
 'benefit',
 'benfost',
 'beniciodeltoro',
 'benjamin',
 'benjaminbratt',
 'benkingsley',
 'bennett',
 'benstil',
 'bent',
 'berlin',
 'berniemac',
 'best',
 'bestfriend',
 'bestfriendsinlov',
 'bet',
 'beth',
 'betray',
 'bettemidl',
 'better',
 'betti',
 'beverli',
 'bibl',
 'bid',
 'big',
 'bigger',
 'biggest',
 'bike',
 'biker',
 'bikini',
 'billhad',
 'billi',
 'billionair',
 'billmurray',
 'billnighi',
 'billpaxton',
 'billpullman',
 'billybobthornton',
 'billyconnolli',
 'billycrudup',
 'billycryst',
 'biographi',
 'biolog',
 'bird',
 'birth',
 'birthday',
 'bisexu',
 'bishop',
 'bit',
 'bite',
 'bitter',
 'bizarr',
 'black',
 'blackmag',
 'blackmail',
 'blackpeopl',
 'blade',
 'blame',
 'blend',
 'blind',
 'bliss',
 'block',
 'blond',
 'blood',
 'bloodi',
 'bloodsplatt',
 'bloodthirsti',
 'blow',
 'blue',
 'board',
 'boardingschool',
 'boat',
 'bob',
 'bobbi',
 'bobbyfarrelli',
 'bobhoskin',
 'bodi',
 'body',
 'bodyguard',
 'bold',
 'bollywood',
 'bomb',
 'bond',
 'bone',
 'bonniehunt',
 'book',
 'border',
 'bore',
 'boredom',
 'born',
 'boss',
 'boston',
 'botch',
 'bound',
 'boundari',
 'bounti',
 'bountyhunt',
 'box',
 'boxer',
 'boy',
 'boyfriend',
 'boys',
 'bradleycoop',
 'bradpitt',
 'brain',
 'brand',
 'brave',
 'braveri',
 'brazil',
 'brazilian',
 'break',
 'breakdown',
 'breakup',
 'breast',
 'breath',
 'breckinmey',
 'breed',
 'brendanfras',
 'brendangleeson',
 'brent',
 'brettratn',
 'brian',
 'briancox',
 'briandepalma',
 'bride',
 'bridesmaid',
 'bridg',
 'brief',
 'brien',
 'bright',
 'brilliant',
 'bring',
 'brink',
 'britain',
 'british',
 'britishsecretservic',
 'brittanymurphi',
 'broadcast',
 'broadway',
 'broke',
 'broken',
 'broker',
 'brook',
 'brooklyn',
 'broom',
 'brothel',
 'brother',
 'brotherbrotherrelationship',
 'brothers',
 'brothersisterrelationship',
 'brought',
 'brown',
 'bruce',
 'brucecampbel',
 'brucedern',
 'brucegreenwood',
 'brucewilli',
 'brutal',
 'bryansing',
 'brycedallashoward',
 'bu',
 'buck',
 'bud',
 'buddi',
 'buddy',
 'buddycomedi',
 'buddycop',
 'budget',
 'build',
 'building',
 'built',
 'bullet',
 'bulli',
 'bumbl',
 'bunch',
 'bunker',
 'bunni',
 'burglar',
 'buri',
 'burn',
 'burtreynold',
 'bush',
 'busi',
 'business',
 'businessman',
 'bust',
 'butcher',
 'butler',
 'butt',
 'button',
 'buy',
 'buzz',
 'cabin',
 'caesar',
 'cage',
 'cairo',
 'cal',
 'california',
 'calvin',
 'camcord',
 'came',
 'camera',
 'cameraman',
 'camerondiaz',
 'camgigandet',
 'camp',
 'campaign',
 'campbell',
 'campu',
 'canada',
 'canadian',
 'cancer',
 'candid',
 'canin',
 'cannib',
 'canuxploit',
 'capabl',
 'caper',
 'capit',
 'capt',
 'captain',
 'captiv',
 'captur',
 'capture',
 'car',
 'caraccid',
 'carchas',
 'carcrash',
 'card',
 'care',
 'career',
 'carefre',
 'caretak',
 'careymulligan',
 'caribbean',
 'carjourney',
 'carl',
 'carlagugino',
 'carmen',
 'carol',
 'carolina',
 'carrac',
 'carri',
 'carrie',
 'cartel',
 'carter',
 'cartoon',
 'caryelw',
 'case',
 'caseyaffleck',
 'cash',
 'casino',
 'cast',
 'castl',
 'cat',
 'cataclysm',
 'catastroph',
 'catch',
 'cateblanchett',
 'catherinedeneuv',
 'catherinekeen',
 'catherineo',
 'catherinezeta',
 'cathol',
 'catholic',
 'cattl',
 'caught',
 'caus',
 'cavalri',
 'cave',
 'cavemen',
 'cedrictheentertain',
 'celebr',
 'celebration',
 'cell',
 'cellphon',
 'cemeteri',
 'center',
 'centr',
 'central',
 'centuri',
 'centuries',
 'century',
 'ceo',
 'certain',
 'chad',
 'chain',
 'chainsaw',
 'challeng',
 'chamber',
 'champion',
 'championship',
 'chanc',
 'chance',
 'chang',
 'change',
 'changed',
 'changes',
 'channingtatum',
 'chao',
 'chaos',
 'chaotic',
 'chapter',
 'charact',
 'character',
 'characters',
 'charg',
 'charismat',
 'charl',
 'charless',
 'charli',
 'charlie',
 'charliesheen',
 'charlizetheron',
 'charm',
 'chart',
 'chase',
 'chauffeur',
 'chazzpalminteri',
 'cheat',
 'check',
 'cheerlead',
 'chef',
 'chemic',
 'cher',
 'chevychas',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childabus',
 'childhero',
 'childhood',
 'childprodigi',
 'children',
 'chill',
 'chimp',
 'china',
 'chines',
 'chip',
 'chipmunk',
 'chiwetelejiofor',
 'chloe',
 'chloëgracemoretz',
 'chloësevigni',
 'chocol',
 'choic',
 'choice',
 'choos',
 'chosen',
 'chowyun',
 'chri',
 'chriscolumbu',
 'chriscoop',
 'chrisevan',
 'chrishemsworth',
 'chrisklein',
 'chrispin',
 'chrispratt',
 'chrisrock',
 'christ',
 'christian',
 'christianbal',
 'christianslat',
 'christin',
 'christinaappleg',
 'christinaricci',
 'christma',
 'christmas',
 'christmasparti',
 'christmastre',
 'christoph',
 'christopherguest',
 'christopherlambert',
 'christopherlloyd',
 'christophernolan',
 'christopherplumm',
 'christopherwalken',
 'christophwaltz',
 'chrisweitz',
 'chronicl',
 'chuck',
 'church',
 'cia',
 'ciaránhind',
 'cigarettesmok',
 'cillianmurphi',
 'cinema',
 'circl',
 'circu',
 'circuit',
 'circumst',
 'citi',
 'citizen',
 'city',
 'civil',
 'civilian',
 'civilwar',
 'claim',
 'clair',
 'clairedan',
 'claireforlani',
 'clan',
 'clark',
 'clash',
 'class',
 'classdiffer',
 'classic',
 'classmat',
 'classroom',
 'claudevandamm',
 'clay',
 'cleaduval',
 'clean',
 'clear',
 'clerk',
 'clever',
 'client',
 'clients',
 'cliff',
 'climat',
 'climb',
 'clinteastwood',
 'cliveowen',
 'clock',
 'clone',
 'close',
 'closer',
 'cloud',
 'clown',
 'club',
 'clue',
 'clueless',
 'clutch',
 'coach',
 'coast',
 'cocain',
 'code',
 'coffin',
 'cohen',
 'col',
 'cold',
 'coldwar',
 'cole',
 'colehaus',
 'colin',
 'colinfarrel',
 'colinfirth',
 'collaps',
 'colleagu',
 'collect',
 'collector',
 'colleg',
 'college',
 'collid',
 'collis',
 'colombia',
 'colonel',
 'coloni',
 'color',
 'colorado',
 'coma',
 'combat',
 'combin',
 'come',
 'comeback',
 'comed',
 'comedi',
 'comedian',
 'comedy',
 'comet',
 'comfort',
 'comic',
 'coming',
 'comingofag',
 'comingout',
 'command',
 'commando',
 'commerci',
 'commiss',
 'commit',
 'common',
 'commun',
 'communist',
 'community',
 'compani',
 'companion',
 'company',
 'compet',
 'competit',
 'competition',
 'complet',
 'complex',
 'complic',
 'compos',
 'compuls',
 'comput',
 'computerviru',
 'conan',
 'concern',
 'concert',
 'concoct',
 'condit',
 'condition',
 'conduct',
 'confeder',
 'confess',
 'confid',
 'confin',
 'conflict',
 'confront',
 'confus',
 'congress',
 'conman',
 'connect',
 'connecticut',
 'connel',
 'connienielsen',
 'connor',
 'conquer',
 'consequ',
 'consequences',
 'conserv',
 'consid',
 'conspir',
 'conspiraci',
 'conspiracy',
 'constant',
 'constantli',
 'construct',
 'consum',
 'contact',
 'contain',
 'contemporari',
 'contend',
 'content',
 'contest',
 'continu',
 'contract',
 'contractor',
 'control',
 'controversi',
 'convent',
 'converg',
 'convers',
 'convict',
 'convinc',
 'cook',
 'cool',
 'cooper',
 'cop',
 'cope',
 'cops',
 'core',
 'corner',
 'corp',
 'corpor',
 'corporation',
 'corps',
 'corrupt',
 ...]

In [38]:
# cosine_similarity will calculate similarity of each movie with every movie
from sklearn.metrics.pairwise import cosine_similarity
similarity=cosine_similarity(vectors)
# similarity is a variable which contains similarity of each movie with others
similarity

array([[1.        , 0.02159364, 0.0306685 , ..., 0.02364218, 0.        ,
        0.        ],
       [0.02159364, 1.        , 0.01274812, ..., 0.01695614, 0.        ,
        0.00629411],
       [0.0306685 , 0.01274812, 1.        , ..., 0.0167251 , 0.        ,
        0.        ],
       ...,
       [0.02364218, 0.01695614, 0.0167251 , ..., 1.        , 0.02054374,
        0.02904047],
       [0.        , 0.        , 0.        , ..., 0.02054374, 1.        ,
        0.02137391],
       [0.        , 0.00629411, 0.        , ..., 0.02904047, 0.02137391,
        1.        ]])

MAIN FUNCTION WHICH WILL FETCH US SIMILAR MOVIES FOR A GIVEN MOVIE

In [39]:
# enumerate functions helps us to have index position of every movie
list(enumerate(similarity[0]))

[(0, 1.0000000000000002),
 (1, 0.02159363658197224),
 (2, 0.030668499257494857),
 (3, 0.03833166209761656),
 (4, 0.11000287710699017),
 (5, 0.045587900808752954),
 (6, 0.016934524555545657),
 (7, 0.07543290530672861),
 (8, 0.01932294423523218),
 (9, 0.024988880205965493),
 (10, 0.031802715474065886),
 (11, 0.03362055382163884),
 (12, 0.024063782369638766),
 (13, 0.00947093361212378),
 (14, 0.04288565181741017),
 (15, 0.01706285550916335),
 (16, 0.019566541428206248),
 (17, 0.06970850456513662),
 (18, 0.06162020931967942),
 (19, 0.027056201342996716),
 (20, 0.020835809689277413),
 (21, 0.041108601970320485),
 (22, 0.01872347156129855),
 (23, 0.02410358648767611),
 (24, 0.011789017902046053),
 (25, 0.046625277262861475),
 (26, 0.07293850740256254),
 (27, 0.1037054863489057),
 (28, 0.041148574190272),
 (29, 0.021810693967215782),
 (30, 0.0179392788203609),
 (31, 0.08400907060495141),
 (32, 0.03667536557849178),
 (33, 0.02389980637439232),
 (34, 0.0),
 (35, 0.02452833701128741),
 (36, 0.10242397780200148),
 (37, 0.03344471501409599),
 (38, 0.0335688584101116),
 (39, 0.0221046683115534),
 (40, 0.024744399459995202),
 (41, 0.0874634625648228),
 (42, 0.0),
 (43, 0.043714411013946526),
 (44, 0.006572546886918944),
 (45, 0.03622530785868147),
 (46, 0.050336490235421055),
 (47, 0.1708430434043131),
 (48, 0.034464495316412984),
 (49, 0.028508990843218687),
 (50, 0.031242915995995883),
 (51, 0.02990817647330821),
 (52, 0.11141130111402707),
 (53, 0.009323304306429601),
 (54, 0.008478045668850971),
 (55, 0.026858024405033393),
 (56, 0.0568977431038269),
 (57, 0.024827020148610986),
 (58, 0.025611308444182905),
 (59, 0.020017105432476336),
 (60, 0.018044183262388786),
 (61, 0.10891278033123525),
 (62, 0.017773883048897227),
 (63, 0.03533804145441924),
 (64, 0.009872381643549028),
 (65, 0.0033741694955118956),
 (66, 0.0065254882291838024),
 (67, 0.08308595106049432),
 (68, 0.056473311975488015),
 (69, 0.0158971365446143),
 (70, 0.01835960208693811),
 (71, 0.019815245306893485),
 (72, 0.04663693990613441),
 (73, 0.013222958221034862),
 (74, 0.12980818070726333),
 (75, 0.05326301046576024),
 (76, 0.018859695786161965),
 (77, 0.011012352288055447),
 (78, 0.01492534233450011),
 (79, 0.017197839795758063),
 (80, 0.021563459145028552),
 (81, 0.045488561215441134),
 (82, 0.03154065474199805),
 (83, 0.10720990840453516),
 (84, 0.05299627624941572),
 (85, 0.060389312049105484),
 (86, 0.03153256859495239),
 (87, 0.05707307068394717),
 (88, 0.03880101593280205),
 (89, 0.0323847314247512),
 (90, 0.019573847157384888),
 (91, 0.07805180593017172),
 (92, 0.02584505478545472),
 (93, 0.02759793372734074),
 (94, 0.11510135431699532),
 (95, 0.0914348050435228),
 (96, 0.020335630048379613),
 (97, 0.01811516033767626),
 (98, 0.01808908980673928),
 (99, 0.005006506416703403),
 (100, 0.021001632078095023),
 (101, 0.02067067888874846),
 (102, 0.04944756010228643),
 (103, 0.029014814137576242),
 (104, 0.011757560524069996),
 (105, 0.049558308681191474),
 (106, 0.019817874913590945),
 (107, 0.015940629082594155),
 (108, 0.08297823354138423),
 (109, 0.02100365704060443),
 (110, 0.012635643616723365),
 (111, 0.06384614042524268),
 (112, 0.018116713992080993),
 (113, 0.013409441984820181),
 (114, 0.013667977873612264),
 (115, 0.013480864142374087),
 (116, 0.013355072256432352),
 (117, 0.020169661674981777),
 (118, 0.01143136701814676),
 (119, 0.027072456735671834),
 (120, 0.0),
 (121, 0.029537656051765504),
 (122, 0.03424235064602389),
 (123, 0.04804528387047695),
 (124, 0.03359684461714885),
 (125, 0.03378849305900388),
 (126, 0.061039423764036635),
 (127, 0.06407875772283568),
 (128, 0.0),
 (129, 0.04044211131902355),
 (130, 0.008199508647523581),
 (131, 0.04130399687871085),
 (132, 0.024134647666294376),
 (133, 0.011160690327845162),
 (134, 0.05675912380996059),
 (135, 0.0),
 (136, 0.006045840224560553),
 (137, 0.019668811657192774),
 (138, 0.04475902395566081),
 (139, 0.055984908145904025),
 (140, 0.023022077975077316),
 (141, 0.045728617363052455),
 (142, 0.04436340099995124),
 (143, 0.02795089342299997),
 (144, 0.011341533032624432),
 (145, 0.004722860233347372),
 (146, 0.014109698104302057),
 (147, 0.011651555445892189),
 (148, 0.036172039929569244),
 (149, 0.10145860478384154),
 (150, 0.09472255439480101),
 (151, 0.09556576663295907),
 (152, 0.020957910894987712),
 (153, 0.03552404818447853),
 (154, 0.0357488075742161),
 (155, 0.012970390413346845),
 (156, 0.026098198197681288),
 (157, 0.03817332862438931),
 (158, 0.07481269029086617),
 (159, 0.016130118425848168),
 (160, 0.054854664081269815),
 (161, 0.011313023877351988),
 (162, 0.0057783186202723085),
 (163, 0.013158641955577078),
 (164, 0.01656836695915951),
 (165, 0.011046689140489617),
 (166, 0.05307583971587844),
 (167, 0.020557531061974735),
 (168, 0.08967265865856877),
 (169, 0.03553999808008912),
 (170, 0.0519465087389477),
 (171, 0.006354928742993544),
 (172, 0.09640049309495284),
 (173, 0.017015976661249422),
 (174, 0.020199048145569044),
 (175, 0.022054298354664218),
 (176, 0.0071988856320316895),
 (177, 0.0),
 (178, 0.006482251825685388),
 (179, 0.040728986725811614),
 (180, 0.0040939955120086495),
 (181, 0.012260899969798277),
 (182, 0.06015249438946235),
 (183, 0.026745991254717074),
 (184, 0.11770622013440685),
 (185, 0.01610426947467744),
 (186, 0.01198278726363354),
 (187, 0.04814029428435464),
 (188, 0.004109906638167782),
 (189, 0.06666776625479409),
 (190, 0.031455208585577384),
 (191, 0.015240021369505497),
 (192, 0.031183587751813523),
 (193, 0.04073598006267999),
 (194, 0.0),
 (195, 0.019379403595519012),
 (196, 0.014060010375583108),
 (197, 0.0134702277669384),
 (198, 0.017110315040523592),
 (199, 0.029583074328084765),
 (200, 0.0313861004465155),
 (201, 0.0),
 (202, 0.007726442038209201),
 (203, 0.02070123695017213),
 (204, 0.019617059964263522),
 (205, 0.01671113190884487),
 (206, 0.058812375047164446),
 (207, 0.018888366609855795),
 (208, 0.038772726001777474),
 (209, 0.012612150688358472),
 (210, 0.027723699440719674),
 (211, 0.00913243183304965),
 (212, 0.01743154737102188),
 (213, 0.021486823658340815),
 (214, 0.0),
 (215, 0.018196858444796772),
 (216, 0.013560353575146743),
 (217, 0.03432656670821747),
 (218, 0.008027044882622073),
 (219, 0.03417941145835825),
 (220, 0.10308675713549048),
 (221, 0.012399216618735276),
 (222, 0.04332120423610752),
 (223, 0.04896961042423884),
 (224, 0.027228582850508422),
 (225, 0.012851939586620335),
 (226, 0.006723363625404661),
 (227, 0.027342933930199338),
 (228, 0.052169418771913584),
 (229, 0.03533698965227845),
 (230, 0.04261481872780576),
 (231, 0.0),
 (232, 0.03279072878525541),
 (233, 0.02682598929711029),
 (234, 0.035227675272211594),
 (235, 0.03501416834406065),
 (236, 0.10192014035134987),
 (237, 0.014430897187253797),
 (238, 0.0499702313863684),
 (239, 0.06416491690895747),
 (240, 0.009436422392855474),
 (241, 0.021758982198925046),
 (242, 0.019875927089774197),
 (243, 0.031689138302067967),
 (244, 0.05146092026690996),
 (245, 0.02740888832698758),
 (246, 0.04456704466796388),
 (247, 0.0),
 (248, 0.008632529875193199),
 (249, 0.08887202984468354),
 (250, 0.0),
 (251, 0.030548181074125602),
 (252, 0.0037356911755914044),
 (253, 0.023969339181035092),
 (254, 0.041002106412413517),
 (255, 0.0),
 (256, 0.04727925536161122),
 (257, 0.013890370186032112),
 (258, 0.005955576757610681),
 (259, 0.013304851554145082),
 (260, 0.12886464502855138),
 (261, 0.004455907154882827),
 (262, 0.045147738482840295),
 (263, 0.022522052274313392),
 (264, 0.0),
 (265, 0.009847896530240943),
 (266, 0.0538315588026952),
 (267, 0.014947297731350222),
 (268, 0.017604080155053634),
 (269, 0.007360430654044537),
 (270, 0.04871639273833896),
 (271, 0.016648333345975586),
 (272, 0.0069106926197754544),
 (273, 0.0039525584627572346),
 (274, 0.044949764838462046),
 (275, 0.08780217358082129),
 (276, 0.017977325098339336),
 (277, 0.019992698582343198),
 (278, 0.08227163423881373),
 (279, 0.07365223282052365),
 (280, 0.0),
 (281, 0.0613142597195638),
 (282, 0.0547848621874282),
 (283, 0.045988282909910035),
 (284, 0.004025306124466936),
 (285, 0.003601780089237638),
 (286, 0.04858643625076685),
 (287, 0.027127127065867777),
 (288, 0.016060103216445437),
 (289, 0.015855895708020002),
 (290, 0.013197167535536014),
 (291, 0.010186763368564656),
 (292, 0.026068783015942988),
 (293, 0.010926825093099567),
 (294, 0.0731992330990257),
 (295, 0.02629449743796522),
 (296, 0.011020058221154096),
 (297, 0.020558754929677656),
 (298, 0.0),
 (299, 0.016512501103699558),
 (300, 0.11120144588630684),
 (301, 0.03288593961817222),
 (302, 0.020417300417063224),
 (303, 0.004892318800585732),
 (304, 0.02763224560356449),
 (305, 0.1140368943024299),
 (306, 0.04153654495114202),
 (307, 0.049603440823426034),
 (308, 0.03382721241981298),
 (309, 0.019698938634683926),
 (310, 0.006214709166618898),
 (311, 0.13036651220445694),
 (312, 0.06659150449534082),
 (313, 0.053156012951744214),
 (314, 0.0),
 (315, 0.022870847222797083),
 (316, 0.0),
 (317, 0.0),
 (318, 0.0),
 (319, 0.029208854223929083),
 (320, 0.005263170299971729),
 (321, 0.0),
 (322, 0.11683778333028091),
 (323, 0.006789945787155944),
 (324, 0.006111543013093862),
 (325, 0.04251205001441988),
 (326, 0.015874086147445614),
 (327, 0.009909411243620271),
 (328, 0.006835698923997261),
 (329, 0.02027789693846718),
 (330, 0.03263177489040398),
 (331, 0.04360773171962461),
 (332, 0.03777622623720791),
 (333, 0.00788223782317987),
 (334, 0.03402568521171356),
 (335, 0.011755079316589595),
 (336, 0.021517620180248477),
 (337, 0.017806412757713334),
 (338, 0.0),
 (339, 0.011596620181233915),
 (340, 0.009833869303221101),
 (341, 0.03640957581083388),
 (342, 0.09112082998960366),
 (343, 0.012221364002061568),
 (344, 0.005463483031222644),
 (345, 0.00445834173843484),
 (346, 0.0),
 (347, 0.0),
 (348, 0.030228333512762648),
 (349, 0.02011605191718025),
 (350, 0.010581145252035528),
 (351, 0.0),
 (352, 0.00693885255330735),
 (353, 0.0168155602980656),
 (354, 0.01186437404484944),
 (355, 0.006687666597477928),
 (356, 0.03097264826720504),
 (357, 0.0),
 (358, 0.017477065713483717),
 (359, 0.008686044021399221),
 (360, 0.007499288643584198),
 (361, 0.03442427564879599),
 (362, 0.04306150757138748),
 (363, 0.04681711392844649),
 (364, 0.01010798563512085),
 (365, 0.04448917678251635),
 (366, 0.01549903728650565),
 (367, 0.0),
 (368, 0.06898278932919039),
 (369, 0.10596479854248164),
 (370, 0.011635326148042385),
 (371, 0.022929594433027535),
 (372, 0.020818614609736042),
 (373, 0.11621802466736504),
 (374, 0.009564449231691557),
 (375, 0.043076273970007),
 (376, 0.01168575747468506),
 (377, 0.0),
 (378, 0.0),
 (379, 0.011994367231409786),
 (380, 0.023090101681767103),
 (381, 0.023291442239743693),
 (382, 0.0),
 (383, 0.00915630279818343),
 (384, 0.0064580782151883965),
 (385, 0.0),
 (386, 0.004224452922128857),
 (387, 0.0048040408042010554),
 (388, 0.0),
 (389, 0.03287127739964286),
 (390, 0.009494931406642749),
 (391, 0.017704907420190843),
 (392, 0.005598210726533938),
 (393, 0.0),
 (394, 0.004357316537296855),
 (395, 0.012936613808459441),
 (396, 0.011533687411991978),
 (397, 0.01197802168286743),
 (398, 0.0),
 (399, 0.005672106541678568),
 (400, 0.025599431357890074),
 (401, 0.021088987124097767),
 (402, 0.02275263745721976),
 (403, 0.022345656605266363),
 (404, 0.04943998877108119),
 (405, 0.022865960586926568),
 (406, 0.012889662218450611),
 (407, 0.007168299837403269),
 (408, 0.006534472252788211),
 (409, 0.0),
 (410, 0.04023829346088199),
 (411, 0.010775470212213312),
 (412, 0.03183419928689528),
 (413, 0.042397425716805714),
 (414, 0.0075653173497994),
 (415, 0.030092233726437212),
 (416, 0.015184722455631683),
 (417, 0.010921457172566542),
 (418, 0.02706560052609997),
 (419, 0.02131128958213282),
 (420, 0.043702734176154466),
 (421, 0.008523589405918913),
 (422, 0.06858658352972397),
 (423, 0.038025736472173326),
 (424, 0.007472749926810605),
 (425, 0.023383376232044627),
 (426, 0.016982360553891726),
 (427, 0.005985207862976604),
 (428, 0.015284511534285684),
 (429, 0.0),
 (430, 0.03859153414109556),
 (431, 0.009297775889353356),
 (432, 0.07551201495819038),
 (433, 0.00600691631251584),
 (434, 0.0),
 (435, 0.013112381948959513),
 (436, 0.0),
 (437, 0.004796537470619316),
 (438, 0.13459474186956039),
 (439, 0.023555510335936742),
 (440, 0.005710226876536417),
 (441, 0.021132311333031416),
 (442, 0.012499287605309384),
 (443, 0.024328738886311194),
 (444, 0.0),
 (445, 0.03857788922002854),
 (446, 0.004264631488097536),
 (447, 0.015505606956157915),
 (448, 0.02032758721472175),
 (449, 0.05564241337587833),
 (450, 0.008111678609967931),
 (451, 0.009252225511341867),
 (452, 0.011898344000537546),
 (453, 0.004278310239682691),
 (454, 0.06911421056164668),
 (455, 0.02302490604233467),
 (456, 0.017952800753788946),
 (457, 0.020193362986106335),
 (458, 0.023250077315129892),
 (459, 0.00935784468262332),
 (460, 0.006438049960029907),
 (461, 0.08034697601213785),
 (462, 0.020008385025196505),
 (463, 0.008125495633621057),
 (464, 0.0),
 (465, 0.0),
 (466, 0.05953725521468999),
 (467, 0.039827958597765584),
 (468, 0.005088314361815961),
 (469, 0.026741358445417123),
 (470, 0.013529021356493098),
 (471, 0.020106155815405525),
 (472, 0.04303774684013071),
 (473, 0.048502478268452956),
 (474, 0.0),
 (475, 0.009372430485434876),
 (476, 0.09569468699378521),
 (477, 0.0),
 (478, 0.01685266081745395),
 (479, 0.0593665507117178),
 (480, 0.049293347835238546),
 (481, 0.0),
 (482, 0.0067139441997730405),
 (483, 0.03666533261760893),
 (484, 0.006999403581526986),
 (485, 0.015584193500267959),
 (486, 0.035429600495754866),
 (487, 0.0624114001070096),
 (488, 0.03586395204388622),
 (489, 0.0),
 (490, 0.036552520880814024),
 (491, 0.04413942218737463),
 (492, 0.051880319947388384),
 (493, 0.010578204248567943),
 (494, 0.0),
 (495, 0.09678139279833446),
 (496, 0.0),
 (497, 0.0),
 (498, 0.018417281030894163),
 (499, 0.0),
 (500, 0.004726426070021023),
 (501, 0.03856100623604558),
 (502, 0.08693968384741874),
 (503, 0.017443134891627472),
 (504, 0.0),
 (505, 0.05422172386789524),
 (506, 0.027169347758628667),
 (507, 0.1458567646782832),
 (508, 0.024299766633150408),
 (509, 0.005358660841889286),
 (510, 0.053159147466551045),
 (511, 0.022354215612290115),
 (512, 0.004979056717386879),
 (513, 0.13191654259111218),
 (514, 0.012779356203644596),
 (515, 0.0056200048324360355),
 (516, 0.006395745075977474),
 (517, 0.0),
 (518, 0.009515048303679816),
 (519, 0.0),
 (520, 0.0),
 (521, 0.005600068345419155),
 (522, 0.00868020947364883),
 (523, 0.010073952152634265),
 (524, 0.0),
 (525, 0.012809188421298976),
 (526, 0.00953484375388089),
 (527, 0.007452940964145251),
 (528, 0.003893644467511474),
 (529, 0.1157277382787049),
 (530, 0.013612251105617607),
 (531, 0.010156869918603328),
 (532, 0.018986132738300913),
 (533, 0.03214939872193496),
 (534, 0.019195990356487204),
 (535, 0.049892599458968345),
 (536, 0.039922018509182616),
 (537, 0.017927254703203777),
 (538, 0.0),
 (539, 0.1532185360573165),
 (540, 0.024721857507545103),
 (541, 0.08025175215499827),
 (542, 0.009759559200398968),
 (543, 0.018522724212540424),
 (544, 0.012027741480896335),
 (545, 0.009254795099659766),
 (546, 0.03139957114453723),
 (547, 0.026086733838475585),
 (548, 0.0),
 (549, 0.07460817473451135),
 (550, 0.017761003628454154),
 (551, 0.008986473582827142),
 (552, 0.0),
 (553, 0.005529882840748134),
 (554, 0.0),
 (555, 0.014646400512127084),
 (556, 0.005132625403072466),
 (557, 0.15596403051439095),
 (558, 0.0),
 (559, 0.0074674425170522234),
 (560, 0.008774368231515119),
 (561, 0.007846931750212081),
 (562, 0.005848807284718169),
 (563, 0.010618248833352772),
 (564, 0.052532621170040254),
 (565, 0.013109687415138859),
 (566, 0.0057089213286827785),
 (567, 0.006161861682243839),
 (568, 0.07193586548959979),
 (569, 0.023509563122081533),
 (570, 0.045648259056087194),
 (571, 0.02161489035472406),
 (572, 0.03864555522898031),
 (573, 0.0037190015450056313),
 (574, 0.0043940674575788236),
 (575, 0.014924793211618655),
 (576, 0.033287435349837725),
 (577, 0.10206971924647931),
 (578, 0.017831098497467918),
 (579, 0.09408154707014546),
 (580, 0.0043672923283650895),
 (581, 0.06477791022379455),
 (582, 0.19403556492982715),
 (583, 0.014487096594915642),
 (584, 0.028165178678977144),
 (585, 0.013815481296170756),
 (586, 0.008794957726664786),
 (587, 0.05877115528542298),
 (588, 0.01596467429327592),
 (589, 0.05922344052966009),
 (590, 0.005924105653521847),
 (591, 0.021597447517613822),
 (592, 0.006171908364256626),
 (593, 0.0),
 (594, 0.010116097939054273),
 (595, 0.11912870664487177),
 (596, 0.03036046644706228),
 (597, 0.01706497449048562),
 (598, 0.009579664568003689),
 (599, 0.022839265481968747),
 (600, 0.01786888881470853),
 (601, 0.009174079015638065),
 (602, 0.04148336709376572),
 (603, 0.009646156077146271),
 (604, 0.01497552013981334),
 (605, 0.015127112068995977),
 (606, 0.0),
 (607, 0.014823719363557065),
 (608, 0.0),
 (609, 0.013452722991239228),
 (610, 0.0182972865504041),
 (611, 0.004168049335970383),
 (612, 0.017326643918620006),
 (613, 0.006623636878214274),
 (614, 0.05152512753902687),
 (615, 0.02962945896258048),
 (616, 0.02119726578383533),
 (617, 0.038914916962578955),
 (618, 0.025518310716196015),
 (619, 0.0),
 (620, 0.0),
 (621, 0.031495893891501474),
 (622, 0.003778503181393153),
 (623, 0.0),
 (624, 0.04533150712640403),
 (625, 0.007126761085318229),
 (626, 0.04874384998766892),
 (627, 0.02918462284744447),
 (628, 0.0),
 (629, 0.024862866674003),
 (630, 0.005931174036147757),
 (631, 0.01409744541617251),
 (632, 0.046557601895571385),
 (633, 0.0040624397176478215),
 (634, 0.039415145444125055),
 (635, 0.06036259673722698),
 (636, 0.009900941197964846),
 (637, 0.005489549948182886),
 (638, 0.007426269266781236),
 (639, 0.0),
 (640, 0.023619554351111557),
 (641, 0.0),
 (642, 0.0),
 (643, 0.06298270262234718),
 (644, 0.011252056072708426),
 (645, 0.009266111940902468),
 (646, 0.047995258201705845),
 (647, 0.06490428319035584),
 (648, 0.006569410740687654),
 (649, 0.0),
 (650, 0.019897218511441397),
 (651, 0.0),
 (652, 0.012108041279818878),
 (653, 0.04010166852649177),
 (654, 0.03398649473654992),
 (655, 0.004295179162933966),
 (656, 0.0),
 (657, 0.008728422542482727),
 (658, 0.012732044334354386),
 (659, 0.005176824133103546),
 (660, 0.021455348581729296),
 (661, 0.09318817696602148),
 (662, 0.0),
 (663, 0.0),
 (664, 0.015622347058773484),
 (665, 0.0146077690842215),
 (666, 0.02794963304313698),
 (667, 0.0),
 (668, 0.06120083509772354),
 (669, 0.025612550170494283),
 (670, 0.00400632926464108),
 (671, 0.029561609546735743),
 (672, 0.01147012937842434),
 (673, 0.007142852176423113),
 (674, 0.043785975833596696),
 (675, 0.01207577879066236),
 (676, 0.005568095630925345),
 (677, 0.004653095655718539),
 (678, 0.04687745206154368),
 (679, 0.0),
 (680, 0.037913939473096445),
 (681, 0.005879261224396675),
 (682, 0.005577583606456328),
 (683, 0.010056084769419405),
 (684, 0.0),
 (685, 0.00606986491646094),
 (686, 0.011432656029592234),
 (687, 0.04495844958554627),
 (688, 0.022824586072464237),
 (689, 0.0),
 (690, 0.008759257166520519),
 (691, 0.011659650010460326),
 (692, 0.08092507199860605),
 (693, 0.012250096563845004),
 (694, 0.00411513218004648),
 (695, 0.013164472204114486),
 (696, 0.013866991520590932),
 (697, 0.0),
 (698, 0.013450574566645912),
 (699, 0.013783698347314495),
 (700, 0.00552314410074145),
 (701, 0.03757148875975234),
 (702, 0.004132322262885781),
 (703, 0.004610087542035884),
 (704, 0.04315581476441594),
 (705, 0.005439712803908312),
 (706, 0.005739647160610986),
 (707, 0.0),
 (708, 0.0045847406755178295),
 (709, 0.0075203933288950225),
 (710, 0.02647903329252098),
 (711, 0.013532974181423761),
 (712, 0.0),
 (713, 0.005670861987038881),
 (714, 0.0),
 (715, 0.025719828912888477),
 (716, 0.006188392679605024),
 (717, 0.0),
 (718, 0.009918716184844741),
 (719, 0.0),
 (720, 0.007850547661046422),
 (721, 0.007948346874202997),
 (722, 0.0),
 (723, 0.008517973759176938),
 (724, 0.004435043880505915),
 (725, 0.0),
 (726, 0.0),
 (727, 0.0064490573683745524),

In [40]:
# movies_new['title']=movies_new['title'].apply(lambda x:x.lower())

In [41]:
def recommend(movie):
    movie_index=movies_new[movies_new['title']==movie].index[0]
    cos_distance=similarity[movie_index] 
    # after this we will sort the similarity with their index and then we will reccommend top 10 similar movies
    movies_list=sorted(list(enumerate(cos_distance)),reverse=True,key=lambda x:x[1])
    movies_list=movies_list[1:11]
    
    for i in movies_list:
        # print(i[0])
       print(movies_new.iloc[i[0]].title)

In [42]:
movies_new.shape
movies_new=movies_new.truncate(after=4804)
movies_new.tail()

,movie_id,title,overview,tags
4800,286939,Sanctuary: Quite a Conundrum,"It should have been just a normal day of sex, ...","it should have been just a normal day of sex, ..."
4801,124606,Bang,A young woman in L.A. is having a bad day: she...,a young woman in l.a. is have a bad day: she' ...
4802,14337,Primer,Friends/fledgling entrepreneurs invent a devic...,friends/fledgl entrepreneur invent a devic in ...
4803,67238,Cavite,"Adam, a security guard, travels from Californi...","adam, a secur guard, travel from california to..."
4804,9367,El Mariachi,El Mariachi just wants to play his guitar and ...,el mariachi just want to play hi guitar and ca...

In [43]:

recommend('Toy Story')

Toy Story 3
Toy Story 2
Small Soldiers
For Your Consideration
The 41–Year–Old Virgin Who Knocked Up Sarah Marshall and Felt Superbad About It
Child's Play
Factory Girl
In the Shadow of the Moon
The Indian in the Cupboard
The Santa Clause 2

In [44]:
import pickle
pickle.dump(movies_new,open('movies.pkl','wb'))
pickle.dump(similarity,open('similarity.pkl','wb'))

In [45]:
movies_new.head()

,movie_id,title,overview,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,a cryptic messag from bond’ past send him on a...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,follow the death of district attorney harvey d...
4,49529,John Carter,"John Carter is a war-weary, former military ca...","john carter is a war-weary, former militari ca..."